spring.application.name=japanese-srs

# ===============================
# Configuración de la BBDD
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/japanese_srs
spring.datasource.username=jrdarcos
spring.datasource.password=jrdarcos

# ===============================
# Configuración de JPA / Hibernate
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# ===============================
# Clave secreta JWT
# ===============================
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970